//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carsAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public car()
        {
            this.carRentalDetails = new HashSet<carRentalDetail>();
        }
    
        public string carNumber { get; set; }
        public Nullable<int> carType { get; set; }
        public bool isAvailable { get; set; }
        public bool isUndamaged { get; set; }
        public Nullable<int> mileage { get; set; }
        public byte[] image { get; set; }
        public int branchId { get; set; }
    
        public virtual branch branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carRentalDetail> carRentalDetails { get; set; }
        public virtual carType carType1 { get; set; }
    }
}
