//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carsAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class carRentalDetail
    {
        public int id { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime returnDate { get; set; }
        public System.DateTime actualReturnDate { get; set; }
        public Nullable<int> userId { get; set; }
        public string carNumber { get; set; }
        public bool isActive { get; set; }
    
        public virtual user user { get; set; }
        public virtual car car { get; set; }
    }
}
